### ISSUE TITLE
The dates shown when editing reservation dates are wrong

### ISSUE THREAD

**Issue by jevers76** [dolson334/banterCustomer#12]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4566149/152598531-2590f4b4-e5be-4cc0-b52f-669c910f8a58.png">
 date the reservation was made is shown, but not the check-in or check-out date.

**Comment by jevers76** [comment]
Shouldn't the check-in and check-out dates match the reservation?

**Comment by dolson334** [comment]
Yes you are correct. Brian has a fix for this he will push tomorrow or Monday.

**Comment by dolson334** [comment]
@jevers76 this is fixed and can be marked complete
