### ISSUE TITLE
unable to delete charges

### ISSUE THREAD

**Issue by jevers76** [dolson334/banterCustomer#22]
deleting a charge with the garbage reported an error message and did not remove the charge.  The error message was 'There was an error removing your charge'. Also can the charge amount be edited?

**Comment by dolson334** [comment]
@jevers76 I cant recreate this. Can you give me a more specific path. Did you add the charge through the POS or directly on the reservation. Side note, you can now open a reservation directly from the calendar. To edit a charge see the image below 

![image](https://user-images.githubusercontent.com/16144247/153125760-18b4c99e-f51a-42b8-80e7-ecbb02852d36.png)

**Comment by jevers76** [comment]
Steps to reproduce:
1.  Add a charge (Gas) to a guest in POS.  This only allows selection selection of active guests (see issue #21)
2. Goto 'Guests'. Search and find guest with gas charge.
3. Try to remove the charge by selecting the trash can.  Charge will not be removed.  Charge amount is not editable here!  The reservation charges are not shown here.
4. The work around is to go to the reservations details and find the guest.  Here the charge can be edited and deleted.

**Comment by dolson334** [comment]
@jevers76 I pushed a fix for this.
