### ISSUE TITLE
booking cabin or boats makes a reservation for the wrong date

### ISSUE THREAD

**Issue by jevers76** [dolson334/banterCustomer#24]
A cabin reservation made for Feb 12-19 using the check availability actually makes the reservation for Feb 11-18.  Similar for boat reservations

**Comment by dolson334** [comment]
@jevers76 you actually caught is in the middle of some date formatting changes for a mac. These will be cleaned up shortly.

**Comment by jevers76** [comment]
Ok,. I will stop using it

**Comment by dolson334** [comment]
@jevers76 should be all set now.
