### ISSUE TITLE
The customer data showing is skewed by one field

### ISSUE THREAD

**Issue by jevers76** [dolson334/banterCustomer#26]
See attachment below.
The first name is in the last name box, the last name is in the age box, etc.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/4566149/153506588-8397456b-728a-44c1-915d-5d56c3b6502d.png">

**Comment by dolson334** [comment]
@jevers76 we have a fix coming for this. Likely tomorrow.

**Comment by jevers76** [comment]
I will close this but might need a new issue unless it is already present.  The total charges in the guest section is showing $0.00
